export {default as email} from './email.svg'
export {default as facebook} from './facebook.svg'
export {default as twitter} from './twitter.svg'
export {default as instagram} from './instagram.svg'
export {default as linkedin} from './linkedin.svg'
export {default as github} from './github.svg'